from __future__ import annotations

from .research_models import generate_ml_ranker_signals_with_config, load_ml_ranker

generate_signals = generate_ml_ranker_signals_with_config
generate_signals_with_config = generate_ml_ranker_signals_with_config

load = load_ml_ranker

