"""Conversion funnel tracker for the family discovery pipeline.

Tracks the full lifecycle from discovered → executed → viable → baseline-beating,
so you can see exactly where candidates drop off and whether discovery is producing
meaningful research signal.

Funnel stages:
  1. discovered       — candidates generated by the LLM in any run
  2. ranked           — candidates with a non-zero ranking_score
  3. promoted         — candidates that reached controlled_probe status
  4. seeded           — IdeaRecords saved to queues/ideas/ with idea_source=family_discovery
  5. proposed         — seeded ideas that appear in at least one proposal's source_idea_ids
  6. executed         — proposals with fd ideas that were actually run (have objective_score)
  7. viable           — executed experiments meeting walk-forward viability threshold
  8. baseline_beating — viable experiments beating the configured momentum baseline

Provenance is tracked at two levels:
  - DIRECT: experiment.source_type == "structural_synthesis" and synthesis_rationale
            references a family_discovery idea_id   (tightly synthesized from the concept)
  - ATTRIBUTED: experiment.source_idea_ids contains at least one family_discovery idea_id
                (idea was present in the proposal batch, may not be directly derived)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[0]))

_BASELINE_SHARPE = 0.722  # S10-005 walk-forward Sharpe


def _load_csv(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        import csv
        with path.open(newline="") as f:
            return list(csv.DictReader(f))
    except Exception:
        return []


def _load_json(path: Path) -> Any:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def _safe_float(val: Any, default: float = 0.0) -> float:
    try:
        if val is None or val == "" or str(val).strip().lower() in {"nan", "none", "null"}:
            return default
        return float(val)
    except (TypeError, ValueError):
        return default


# ---------------------------------------------------------------------------
# Stage 1-2: discovered + ranked — from discovery reports
# ---------------------------------------------------------------------------

def _funnel_from_reports(workspace_root: str) -> dict[str, Any]:
    reports_dir = Path(workspace_root) / "reports" / "family_discovery"
    discovered: list[dict[str, Any]] = []
    ranked: list[dict[str, Any]] = []

    report_paths = sorted(reports_dir.glob("discovery_*.json")) if reports_dir.exists() else []
    # Also try latest.json for current session
    latest = reports_dir / "latest.json"
    if latest.exists():
        d = _load_json(latest)
        if d and d.get("batch_id") and not any(
            r.get("batch_id") == d.get("batch_id") for r in discovered
        ):
            report_paths_set = {p.name for p in report_paths}
            if f"{d['batch_id']}.json" not in report_paths_set:
                report_paths = [latest] + list(report_paths)

    seen_batches: set[str] = set()
    for rp in report_paths:
        report = _load_json(rp)
        if not report:
            continue
        batch_id = report.get("batch_id") or str(rp.name)
        if batch_id in seen_batches:
            continue
        seen_batches.add(batch_id)

        candidates = report.get("candidates") or report.get("ranked_candidates") or []
        for c in candidates:
            cname = str(c.get("family_name") or c.get("name") or "")
            if not cname:
                continue
            entry = {
                "family_name": cname,
                "batch_id": batch_id,
                "ranking_score": _safe_float(c.get("ranking_score") or c.get("effective_score"), 0.0),
                "orthogonality_score": _safe_float(c.get("orthogonality_score"), 0.0),
                "repeat_penalty": _safe_float(c.get("repeat_penalty"), 0.0),
                "is_fresh": bool(c.get("is_fresh_family", True)),
            }
            discovered.append(entry)
            if entry["ranking_score"] > 0.0:
                ranked.append(entry)

    return {"discovered": discovered, "ranked": ranked}


# ---------------------------------------------------------------------------
# Stage 3: promoted — from candidate store
# ---------------------------------------------------------------------------

def _funnel_promoted(workspace_root: str) -> list[dict[str, Any]]:
    try:
        from agents.schemas import load_family_candidates
        candidates = load_family_candidates(workspace_root)
        return [
            {
                "family_name": c.get("family_name") or c.get("name") or "",
                "candidate_id": c.get("candidate_id") or "",
                "ranking_score": _safe_float(c.get("ranking_score"), 0.0),
                "promoted_at": c.get("promoted_at") or c.get("updated_at") or "",
            }
            for c in candidates
            if c.get("status") == "controlled_probe"
        ]
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Stage 4: seeded — from queues/ideas/
# ---------------------------------------------------------------------------

def _funnel_seeded(workspace_root: str) -> list[dict[str, Any]]:
    ideas_dir = Path(workspace_root) / "queues" / "ideas"
    if not ideas_dir.exists():
        return []
    seeded = []
    for fp in ideas_dir.glob("idea_family_discovery_*.json"):
        d = _load_json(fp)
        if not d:
            continue
        seeded.append({
            "idea_id": d.get("idea_id") or fp.stem,
            "family": d.get("family") or "unknown",
            "status": d.get("status") or "new",
            "priority": _safe_float(d.get("priority"), 0.0),
            "novelty_score": _safe_float(d.get("novelty_score"), 0.0),
            "template_similarity_class": d.get("template_similarity_class") or "unknown",
            "family_name": (d.get("suggested_config") or {}).get("family_discovery_candidate") or "",
        })
    return seeded


# ---------------------------------------------------------------------------
# Stage 5: proposed — from proposals index.csv
# ---------------------------------------------------------------------------

def _funnel_proposed(workspace_root: str, seeded_idea_ids: set[str]) -> list[dict[str, Any]]:
    """Find proposals that contain at least one family_discovery idea.

    Checks three places:
    1. source_idea_ids field in proposal.json (non-compact format)
    2. Per-spec metadata in proposal.json (compact format with candidate_configs)
    3. Inferred from experiment index: proposals where at least one executed experiment
       has a family_discovery idea in source_idea_ids (most reliable for compact format)
    """
    # Method 3 (most reliable): infer from executed experiment records
    index_path = Path(workspace_root) / "experiments" / "index.csv"
    if index_path.exists():
        try:
            import csv
            proposal_ids: set[str] = set()
            with index_path.open(newline="") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    src_ids = str(row.get("source_idea_ids") or "")
                    if "family_discovery" not in src_ids:
                        continue
                    prop_id = row.get("source_proposal_id") or ""
                    if prop_id:
                        proposal_ids.add(prop_id)
            return [{"proposal_id": pid, "fd_idea_ids": [], "n_candidates": 0} for pid in sorted(proposal_ids)]
        except Exception:
            pass

    # Fallback: scan proposal directory
    proposals_dir = Path(workspace_root) / "experiments" / "proposals"
    if not proposals_dir.exists():
        return []
    proposed = []
    for pdir in proposals_dir.iterdir():
        if not pdir.is_dir():
            continue
        pfile = pdir / "proposal.json"
        if not pfile.exists():
            continue
        d = _load_json(pfile)
        if not d:
            continue
        raw_ids = d.get("source_idea_ids") or []
        if isinstance(raw_ids, str):
            try:
                raw_ids = json.loads(raw_ids)
            except Exception:
                raw_ids = []
        fd_ids = [x for x in (raw_ids or []) if "family_discovery" in str(x)]
        if fd_ids:
            proposed.append({
                "proposal_id": pdir.name,
                "fd_idea_ids": fd_ids,
                "n_candidates": len((d.get("candidate_configs") or {}).get("momentum") or []),
            })
    return proposed


# ---------------------------------------------------------------------------
# Stage 6-8: executed / viable / baseline-beating — from experiments/index.csv
# ---------------------------------------------------------------------------

def _funnel_executed(workspace_root: str) -> dict[str, Any]:
    index_path = Path(workspace_root) / "experiments" / "index.csv"
    rows = _load_csv(index_path)
    if not rows:
        return {
            "attributed": [],
            "direct": [],
            "viable": [],
            "baseline_beating": [],
        }

    attributed: list[dict[str, Any]] = []
    direct: list[dict[str, Any]] = []

    for row in rows:
        src_ids = str(row.get("source_idea_ids") or "")
        synth_rat = str(row.get("synthesis_rationale") or "")
        if "family_discovery" not in src_ids:
            continue
        score = _safe_float(row.get("objective_score"), None)  # type: ignore[arg-type]
        if score is None:
            continue
        entry = {
            "experiment_id": row.get("experiment_id") or "",
            "strategy_family": row.get("strategy_family") or "",
            "objective_score": score,
            "sharpe": _safe_float(row.get("sharpe"), 0.0),
            "viable": str(row.get("viable") or "").strip().lower() in {"true", "1", "yes"},
            "source_type": row.get("source_type") or "",
            "source_idea_ids": src_ids,
        }
        attributed.append(entry)
        # Direct synthesis: either the new dedicated source_type, or synthesis_rationale
        # containing the family_discovery marker (legacy check)
        src_type = str(row.get("source_type") or "")
        if src_type == "family_discovery_direct_synthesis" or "family_discovery" in synth_rat:
            direct.append(entry)

    viable = [e for e in attributed if e["viable"]]
    baseline_beating = [e for e in viable if e["objective_score"] > _BASELINE_SHARPE]

    return {
        "attributed": attributed,
        "direct": direct,
        "viable": viable,
        "baseline_beating": baseline_beating,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _latest_fd_probe_lane_state(workspace_root: str) -> dict[str, Any]:
    """Extract fd_probe_lane state from the most recent executed proposal."""
    proposals_dir = Path(workspace_root) / "experiments" / "proposals"
    if not proposals_dir.exists():
        return {}
    # Scan proposal dirs sorted by mtime descending
    pdirs = sorted(
        (p for p in proposals_dir.iterdir() if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for pdir in pdirs[:10]:
        pfile = pdir / "proposal.json"
        if not pfile.exists():
            continue
        d = _load_json(pfile)
        if not d:
            continue
        # The fd_probe_lane state is in reasoning_summary per family
        rsummary = d.get("reasoning_summary") or {}
        for fam_data in rsummary.values():
            if not isinstance(fam_data, dict):
                continue
            lane = fam_data.get("fd_probe_lane")
            if lane:
                return {
                    "proposal_id": pdir.name,
                    "family": next(iter(rsummary), "unknown"),
                    **lane,
                }
    return {"note": "no_proposal_with_fd_probe_lane_yet"}


def build_funnel(workspace_root: str = ".") -> dict[str, Any]:
    """Build the full conversion funnel report."""
    report_data = _funnel_from_reports(workspace_root)
    discovered = report_data["discovered"]
    ranked = report_data["ranked"]
    promoted = _funnel_promoted(workspace_root)
    seeded = _funnel_seeded(workspace_root)
    seeded_ids = {s["idea_id"] for s in seeded}
    proposed = _funnel_proposed(workspace_root, seeded_ids)
    executed_data = _funnel_executed(workspace_root)

    attributed = executed_data["attributed"]
    direct = executed_data["direct"]
    viable = executed_data["viable"]
    baseline_beating = executed_data["baseline_beating"]

    def _pct(num: int, denom: int) -> str:
        if denom == 0:
            return "n/a"
        return f"{100.0 * num / denom:.1f}%"

    n_disc = len(discovered)
    n_ranked = len(ranked)
    n_prom = len(promoted)
    n_seed = len(seeded)
    n_prop = len(proposed)
    n_exec = len(attributed)
    n_viable = len(viable)
    n_beat = len(baseline_beating)

    # Compute idea-level coverage: how many seeded ideas appear in proposals / experiments
    n_ideas_proposed = len({
        ib["idea_id"]
        for ib in [
            {"idea_id": s["idea_id"]}
            for s in seeded
        ]
        if any(
            ib["idea_id"] in p.get("fd_idea_ids", []) or True  # all seeded ideas assumed in proposal set
            for p in proposed[:1]
        )
    }) if proposed else 0
    n_ideas_in_exps = sum(
        1 for s in seeded
        if any(s["idea_id"] in e["source_idea_ids"] for e in attributed)
    )

    funnel_stages = [
        {"stage": "discovered",        "count": n_disc,      "conversion": "100%"},
        {"stage": "ranked",            "count": n_ranked,    "conversion": _pct(n_ranked, n_disc)},
        {"stage": "promoted",          "count": n_prom,      "conversion": _pct(n_prom, n_disc)},
        {"stage": "seeded",            "count": n_seed,      "conversion": _pct(n_seed, n_prom)},
        {"stage": "proposals_touched", "count": n_prop,      "conversion": f"{n_ideas_in_exps}/{n_seed} ideas in exps"},
        {"stage": "executed_attributed","count": n_exec,     "conversion": _pct(n_viable, n_exec) + " viable"},
        {"stage": "executed_direct",   "count": len(direct), "conversion": _pct(len(direct), n_exec)},
        {"stage": "viable",            "count": n_viable,    "conversion": _pct(n_viable, n_exec)},
        {"stage": "baseline_beating",  "count": n_beat,      "conversion": _pct(n_beat, n_viable)},
    ]

    # Top executed experiments by score
    top_attributed = sorted(attributed, key=lambda x: -x["objective_score"])[:5]

    # Per-idea breakdown
    idea_breakdown: list[dict[str, Any]] = []
    for s in seeded:
        iid = s["idea_id"]
        iid_exps = [e for e in attributed if iid in e["source_idea_ids"]]
        idea_breakdown.append({
            "idea_id": iid,
            "family_name": s["family_name"],
            "status": s["status"],
            "template_similarity_class": s["template_similarity_class"],
            "experiments_attributed": len(iid_exps),
            "viable_count": sum(1 for e in iid_exps if e["viable"]),
            "best_score": max((e["objective_score"] for e in iid_exps), default=None),
        })

    # Bottleneck identification
    bottleneck = None
    if n_disc == 0:
        bottleneck = "No candidates discovered yet — run family discovery first"
    elif n_ranked == 0:
        bottleneck = "All candidates unranked — clustering step may be failing"
    elif n_prom == 0:
        bottleneck = "No promotions — check max_active_probes cap or probe_budget"
    elif n_seed == 0:
        bottleneck = "No ideas seeded — check seed_ideas_for_probe flag and probe_budget"
    elif n_prop == 0:
        bottleneck = "Ideas seeded but not reaching proposals — check use_idea_queue and idea status"
    elif n_exec == 0:
        bottleneck = "Proposals exist but no executed experiments — run autonomous cycles with --run-proposal"
    elif len(direct) == 0:
        bottleneck = (
            "Executed but all co-attributed (0 direct syntheses). "
            "Structural execution lane may be skipped in confirmation mode, "
            "or configs are near-duplicates. Run in broader_exploration mode."
        )
    elif n_viable == 0:
        bottleneck = "Experiments executed but none viable — probe configs may need tuning"
    else:
        bottleneck = None  # pipeline healthy

    # Check the most recent proposal for fd probe lane state
    fd_probe_lane = _latest_fd_probe_lane_state(workspace_root)

    return {
        "funnel_stages": funnel_stages,
        "bottleneck": bottleneck,
        "top_attributed_experiments": top_attributed,
        "idea_breakdown": idea_breakdown,
        "direct_synthesis_count": len(direct),
        "total_attributed": n_exec,
        "total_viable": n_viable,
        "total_baseline_beating": n_beat,
        "baseline_sharpe": _BASELINE_SHARPE,
        "seeded_ideas": seeded,
        "promoted_candidates": promoted,
        "n_proposals_with_fd_ideas": n_prop,
        "fd_probe_lane": fd_probe_lane,
    }


def print_funnel(workspace_root: str = ".") -> None:
    """Print the conversion funnel to stdout."""
    funnel = build_funnel(workspace_root)

    print("\n=== FAMILY DISCOVERY CONVERSION FUNNEL ===")
    print(f"{'Stage':<30} {'Count':>6}  {'Conv':>7}")
    print("-" * 46)
    for stage in funnel["funnel_stages"]:
        print(f"{stage['stage']:<30} {stage['count']:>6}  {stage['conversion']:>7}")

    bn = funnel.get("bottleneck")
    if bn:
        print(f"\n[BOTTLENECK] {bn}")
    else:
        print("\n[OK] Pipeline healthy — discovery is producing executed experiments")

    # Top 5 experiments
    top = funnel.get("top_attributed_experiments") or []
    if top:
        print("\n=== TOP ATTRIBUTED EXPERIMENTS ===")
        for e in top:
            viable_tag = "VIABLE" if e["viable"] else "not viable"
            print(f"  {e['experiment_id'][:60]}  score={e['objective_score']:.4f}  [{viable_tag}]")

    # Idea breakdown
    breakdown = funnel.get("idea_breakdown") or []
    if breakdown:
        print("\n=== IDEA BREAKDOWN ===")
        for ib in breakdown:
            best = f"{ib['best_score']:.4f}" if ib["best_score"] is not None else "none"
            print(
                f"  {ib['family_name'][:35]:<35} "
                f"status={ib['status']:<12}  "
                f"class={ib['template_similarity_class']:<20}  "
                f"attributed={ib['experiments_attributed']:4}  "
                f"viable={ib['viable_count']:3}  "
                f"best={best}"
            )

    direct = funnel.get("direct_synthesis_count", 0)
    total = funnel.get("total_attributed", 0)
    print(f"\nDirect synthesis: {direct}/{total} attributed experiments")
    print(f"Baseline ({funnel['baseline_sharpe']:.3f}): {funnel['total_baseline_beating']} experiments beat it")

    # FD probe lane reservation status
    lane = funnel.get("fd_probe_lane") or {}
    if lane and "note" not in lane:
        confirmation_reserved = lane.get("confirmation_mode") and lane.get("executed_count", 0) > 0
        print(f"\n=== FD PROBE LANE (most recent proposal) ===")
        print(f"  available_ideas={lane.get('available_ideas', 0)}  "
              f"reservation_budget={lane.get('reservation_budget', 0)}  "
              f"executed={lane.get('executed_count', 0)}  "
              f"confirmation_mode={lane.get('confirmation_mode', False)}  "
              f"confirmation_reserved={confirmation_reserved}")
        if lane.get("entries"):
            for e in lane["entries"]:
                print(f"    [{e.get('synth_class','?')}] {e.get('family_name','?')}")
        skip = lane.get("skip_reason")
        if skip and lane.get("executed_count", 0) == 0:
            print(f"  skip_reason: {skip}")
    print()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Family discovery conversion funnel")
    parser.add_argument("--workspace-root", default=".", help="Repo root")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    args = parser.parse_args()

    funnel = build_funnel(args.workspace_root)
    if args.json:
        print(json.dumps(funnel, indent=2, default=str))
    else:
        print_funnel(args.workspace_root)
